version: '3.8'

services:
  stats-server:
    build: ./stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stat_service
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  stats-db:
    image: postgres:16.1
    container_name: postgres-stats
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: stat_service
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER"]
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ./main-service
    image: main-service
    container_name: evm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/main_service
      SPRING_DATASOURCE_USERNAME: main
      SPRING_DATASOURCE_PASSWORD: main
      STAT_SERVER_URL: http://stats-server:9090
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  ewm-db:
    image: postgres:16.1
    container_name: postgres-main
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: main_service
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER"]
      timeout: 5s
      interval: 5s
      retries: 10