services:
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container-local
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: stats-db
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats

  main-db:
    image: postgres:14-alpine
    container_name: main-local
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main