DROP TABLE IF EXISTS hits;

CREATE TABLE hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(64),
    uri       VARCHAR(128),
    ip        VARCHAR(32),
    timestamp timestamp WITHOUT TIME ZONE
    );
